version: '3.8'

services:
  postgresql:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - postgresql-vol:/var/lib/postgresql/data
    networks:
      - sonar-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sonar"]
      interval: 20s
      timeout: 10s
      retries: 5

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube-container
    ports:
      - "9000:9000"
    environment:
      SONARQUBE_JDBC_URL: jdbc:postgresql://postgresql:5432/sonarqube
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-logs:/opt/sonarqube/logs
      - sonarqube-extensions:/opt/sonarqube/extensions
    networks:
      - sonar-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  postgresql-vol:
  sonarqube-data:
  sonarqube-logs:
  sonarqube-extensions:

networks:
  sonar-network:
    driver: bridge
